name: Run WDIO Tests on BrowserStack

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allows manual trigger

jobs:
  wdio-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Updated to latest
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: npm install

    - name: Set BrowserStack credentials
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: echo "BrowserStack credentials set"

    - name: Run WDIO Tests
      run: npx wdio run wdio.conf.js

    - name: Zip Test Reports
      run: |
        mkdir -p artifact
        zip -r artifact/reports.zip ./reports

    - name: Upload Test Report as Artifact
      uses: actions/upload-artifact@v4  # Updated to latest
      with:
        name: test-reports
        path: artifact/reports.zip
        compression-level: 9   # Maximum compression
